

KLINE_INTERVAL_1MIN = "1min"
KLINE_INTERVAL_15MIN = "15min"
KLINE_INTERVAL_1HOUR = "1hour"
KLINE_INTERVAL_4HOUR = "1hour"
KLINE_INTERVAL_1DAY = "1day"
KLINE_INTERVAL_1WEEK = "1week"


TRADE_TYPE_FUTURE = "future"
TRADE_TYPE_SWAP = "swap"
TRADE_TYPE_MARGIN = "margin"
TRADE_TYPE_SPOT = "spot"


EXCHANGE_OKEX = "okex"
EXCHANGE_HUOBI = "huobi"
EXCHANGE_BINANCE = "binance"

CONTRACT_TYPE_THIS_WEEK = "this_week"
CONTRACT_TYPE_NEXT_WEEK = "next_week"
CONTRACT_TYPE_QUARTER = "quarter"
