BIRTHDAY_BTC = "2009-01-03 00:00:00"

HALVING_TIMESTAMP_BTC = [
    1354032000000,
    1467993600000,
    1588176000000,
]

HALVING_DATETIME_BTC = [
    "2012-11-28 00:00:00",
    "2016-07-09 00:00:00",
    "2020-04-30 00:00:00",
]

MODE_BACKTEST = "backtest"
MODE_STRATEGY = "strategy"
MODE_ONLINE = "online"
MODE_OFFLINE = "offline"

KLINE_INTERVAL_1MIN = "1min"
KLINE_INTERVAL_15MIN = "15min"
KLINE_INTERVAL_1HOUR = "1hour"
KLINE_INTERVAL_4HOUR = "4hour"
KLINE_INTERVAL_1DAY = "1day"
KLINE_INTERVAL_1WEEK = "1week"

TRADE_TYPE_FUTURE = "future"
TRADE_TYPE_SWAP = "swap"
TRADE_TYPE_MARGIN = "margin"
TRADE_TYPE_SPOT = "spot"

EXCHANGE_OKEX = "okex"
EXCHANGE_HUOBI = "huobi"
EXCHANGE_BINANCE = "binance"
EXCHANGE_COINBASE = "coinbase"
EXCHANGE_BITSTAMP = "bitstamp"

CONTRACT_TYPE_THIS_WEEK = "this_week"
CONTRACT_TYPE_NEXT_WEEK = "next_week"
CONTRACT_TYPE_QUARTER = "quarter"
CONTRACT_TYPE_NONE = "none"

PARAM_TYPE_STRING = "string"
PARAM_TYPE_INTEGER = "integer"
PARAM_TYPE_FLOAT = "float"

INDICES_INTERVAL_1MIN = "1min"
INDICES_INTERVAL_15MIN = "15min"
INDICES_INTERVAL_1HOUR = "1hour"
INDICES_INTERVAL_4HOUR = "4hour"
INDICES_INTERVAL_1DAY = "1day"
INDICES_INTERVAL_1WEEK = "1week"

INDICES_TYPE_STRING = "string"
INDICES_TYPE_INTEGER = "integer"
INDICES_TYPE_FLOAT = "float"

SETTLE_MODE_BASIS = 1
SETTLE_MODE_COUNTER = 2

SUBJECT_INVEST = "invest"
SUBJECT_DIVEST = "divest"
SUBJECT_SETTLE = "settle"
SUBJECT_INJECTION = "injection"  # 注资，amount为正， position 为0，计算子账户资产时需要剔除。
SUBJECT_DIVIDEND = "dividend"  # 分红，amount为负， position 为0，计算子账户资产时需要剔除，也就是说分红仅从总账户中提取。
SUBJECT_FREEZE = "freeze"  # 冻结，amount为负， position 为正
SUBJECT_UNFREEZE = "unfreeze"  # 解冻，amount为正， position 为负
SUBJECT_INCOME = "income"  # 收益，amount正负皆可， position 为0
SUBJECT_TRANSACTION_FEE = "transaction_fee"  # 交易费用，amount正负皆可， position 为0
SUBJECT_LOAN_FEE = "loan_fee"  # 借贷费用，amount为负， position 为0
SUBJECT_ADJUSTMENT = "adjustment"  # 与交易所服务器进行校准，amount正负皆可， position 为0
SUBJECT_TRANSFER_IN = "transfer_in"  # 内部转账，转入子账户，amount为正， position 为0，计算总账户资产时需要剔除。
SUBJECT_TRANSFER_OUT = "transfer_out"  # 内部转账，转出子账户，amount为负， position 为0，计算总账户资产时需要剔除。

ORDER_TYPE_OPEN_LONG = 1
ORDER_TYPE_OPEN_SHORT = 2
ORDER_TYPE_LIQUIDATE_LONG = 3
ORDER_TYPE_LIQUIDATE_SHORT = 4

ORDER_STATUS_UNFINISH = 0
ORDER_STATUS_PART_FINISH = 1
ORDER_STATUS_FINISH = 2
ORDER_STATUS_CANCEL = 3
ORDER_STATUS_REJECT = 4
ORDER_STATUS_CANCEL_ING = 5
ORDER_STATUS_FAIL = 6

ORDER_PLACE_TYPE_T_MAKER = "t_maker"
ORDER_PLACE_TYPE_B_MAKER = "b_maker"
ORDER_PLACE_TYPE_T_TAKER = "t_taker"
ORDER_PLACE_TYPE_B_TAKER = "b_taker"
ORDER_PLACE_TYPE_O_SWAP = "o_swap"
ORDER_PLACE_TYPE_L_SWAP = "l_swap"
ORDER_PLACE_TYPE_MARKET = "market"

INSTANCE_STATUS_WAITING = 0
INSTANCE_STATUS_OPENING = 1
INSTANCE_STATUS_LIQUIDATING = 2
INSTANCE_STATUS_FINISHED = 3
INSTANCE_STATUS_ERROR = 9

INTERVAL_1MIN = "1min"
INTERVAL_15MIN = "15min"
INTERVAL_1HOUR = "1hour"
INTERVAL_4HOUR = "4hour"
INTERVAL_8HOUR = "8hour"
INTERVAL_1DAY = "1day"
INTERVAL_1WEEK = "1week"
