CREATE TABLE `future_kline_eth_usd` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `open` decimal(20,8) NOT NULL DEFAULT '0.0' COMMENT 'The kline open price',
  `high` decimal(20,8) NOT NULL DEFAULT '0.0' COMMENT 'The kline high price',
  `low` decimal(20,8) NOT NULL DEFAULT '0.0' COMMENT 'The kline low price',
  `close` decimal(20,8) NOT NULL DEFAULT '0.0' COMMENT 'The kline close price',
  `vol` decimal(20, 8) NOT NULL DEFAULT '0' COMMENT 'The kline volume',
  `symbol` varchar(30) NOT NULL DEFAULT '' COMMENT 'The symbol: eth_usd',
  `exchange` varchar(20) NOT NULL DEFAULT '' COMMENT 'The exchange name: okex/binance',
  `contract_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'contracty type: this_week/next_week/quarter',
  `interval` varchar(10) NOT NULL DEFAULT '1min' COMMENT 'The kline interval: 1min/15min/1h/4h/1day/1week',
  `timestamp` bigint(13) NOT NULL DEFAULT '0' COMMENT 'The kline start timestamp',
  `date` datetime NOT NULL COMMENT 'The kline start date',
  `due_timestamp` bigint(13) DEFAULT '0' COMMENT 'The contract due timestamp',
  `due_date` datetime NOT NULL COMMENT 'The contract due date',
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `symbol` (`symbol`,`exchange`,`contract_type`,`interval`,`date`,`due_date`),
  KEY `date` (`date`),
  KEY `timestamp` (`timestamp`),
  KEY `due_date` (`due_date`),
  KEY `symbol_2` (`symbol`,`exchange`,`contract_type`,`interval`,`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
