CREATE TABLE `future_order_set` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sid` varchar(20) NOT NULL COMMENT 'order set id',
  `sequence` tinyint(2) NOT NULL COMMENT 'order sid sequence',
  `type` tinyint(1) NOT NULL COMMENT '1:open_long, 2:open_short, 3: liquidate_long, 4: liquidate_short',
  `remote_order_id` varchar(50) DEFAULT '' COMMENT 'order sid sequence',
  `price` bigint(20) NOT NULL COMMENT 'unit: 0.00000001',
  `amount` int(11) NOT NULL,
  `avg_price` bigint(11) COMMENT 'unit: 0.00000001',
  `deal_amount` int(11),
  `status` tinyint(4),
  `place_type` tinyint(4),
  `lever` int(11),
  `fee` decimal(20,8),
  `symbol` varchar(20),
  `exchange` varchar(20),
  `contract_type` varchar(20),
  `contract_name` varchar(20),
  PRIMARY KEY (`id`),
  UNIQUE KEY `sid` (`sid`,`sequence`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;