CREATE TABLE `future_strategy_instance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `symbol` varchar(30) NOT NULL,
  `exchange` varchar(20) NOT NULL,
  `direction` varchar(20) NOT NULL,
  `status` varchar(20) NOT NULL COMMENT 'status: wait_open_upper/wait_open_lower/opening/opened/wait_liquidate_upper/wait_liquidate_lower/liquidating/liquidated/error',
  `position` decimal(8,2) NOT NULL COMMENT 'the strategy use account asset scale, sometime you do not want use full asset to open',
  `strategy` varchar(20) NOT NULL COMMENT 'the strategy name',
  `unit_amount` int(11) COMMENT 'the unit amount',
  `lever` int(11) COMMENT 'the trade lever',
  `degree` varchar(30) COMMENT 'the degree on the direction: heavy/medium/light',
  `due_timestamp` bigint(13) COMMENT 'the due timestamp',
  `due_date` datetime COMMENT 'the due date',
--  `open_order_id` varchar(255) DEFAULT NULL,
  `open_contract_type` varchar(20) COMMENT 'the contract type when open',
  `open_amount` int(11) COMMENT 'the amount wanted to open',
  `open_deal_amount` int(11) COMMENT 'the opened amount',
  `open_price` bigint(20) COMMENT 'the price wanted to deal, the unit is 0.00000001',
  `open_price_avg` bigint(20) COMMENT 'the avg price when opened, the unit is 0.00000001',
  `open_timestamp` bigint(13) COMMENT 'the open timestamp',
  `open_date` datetime COMMENT 'the open date',
--  `liquidate_order_id` varchar(255) DEFAULT NULL,
  `liquidate_contract_type` varchar(20) COMMENT 'the contract type when liquidate',
  `liquidate_amount` int(11) COMMENT 'the amount wanted to liquidate',
  `liquidate_deal_amount` int(11) COMMENT 'the liquidated amount',
  `liquidate_price` bigint(20) COMMENT 'the price wanted to deal, the unit is 0.00000001',
  `liquidate_price_avg` bigint(20) COMMENT 'the avg price when liquidated, the unit is 0.00000001',
  `liquidate_timestamp` bigint(13) COMMENT 'the liquidate timestamp',
  `liquidate_date` datetime COMMENT 'the liquidate date',
-- some columns about the account
  `anchored_asset` decimal(20,8) COMMENT 'anchored asset when open',
  `margined_asset` decimal(20,8) COMMENT 'margined asset when open, the future account asset must gt anchored_asset',
  `open_fee` decimal(20,8) COMMENT 'the open order set fee',
  `liquidate_fee` decimal(20,8) COMMENT 'the liquidate order set fee',
  `interval` varchar(20) NOT NULL COMMENT 'the strategy logic generate interval: 1h/4h/1day/1week',
  `start_timestamp` bigint(13) NOT NULL COMMENT 'the strategy logic start timestamp',
  `end_timestamp` bigint(13) NOT NULL COMMENT 'the strategy logic end timestamp',
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `symbol` (`symbol`,`exchange`,`open_contract_type`,`strategy`,`interval`,`start_timestamp`),
  KEY `due_timestamp` (`due_timestamp`),
  KEY `open_timestamp` (`open_timestamp`),
  KEY `liquidate_timestamp` (`liquidate_timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
